### ISSUE TITLE
gauth error "Fragment not allowed"

### ISSUE THREAD

**Issue by phpmoli** [bluzi/awesome-google-tasks#14]
Hello,

I wanted to try your app, ive got 2 problems so far:

1) I do not allow third party cookies by default, so the app logs an error to the console: `Uncaught (in promise) {error: "idpiframe_initialization_failed", details: "Cookies are not enabled in current environment."}`
It should catch that exception and pop up a message to the user

2) I allowed the cookies, still doesnt work, it gives me a page after giving the permission: 
```400. That’s an error.
Error: invalid_request
Invalid parameter value for redirect_uri: Fragment not allowed: https://awesomegoogletasks.com/#scope=openid%20email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/tasks%20https://www.googleapis.com/auth/userinfo.profile&id_token=aaaaaaaa&login_hint=aaaaaaaa&client_id=11111111-aaaaaaaa.apps.googleusercontent.com
Request Details
redirect_uri=https://awesomegoogletasks.com/#scope=openid%20email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/tasks&id_token=aaaaaaaa&login_hint=aaaaaaaa&client_id=11111111-aaaaaaaa.apps.googleusercontent.com
response_type=permission id_token
scope=email profile openid https://www.googleapis.com/auth/tasks
openid.realm=
client_id=11111111-aaaaaaaa.apps.googleusercontent.com
ss_domain=https://awesomegoogletasks.com
fetch_basic_profile=true
gsiwebsdk=2
```

Can you please help me setting it up?

**Comment by bluzi** [comment]
hi, thanks for reporting this issue.

few questions:
- what browser and operation system are you using?
- if your browser supports incognito, can you try browsing using incognito with cookies enabled?

**Comment by phpmoli** [comment]
Thanks for your reply.
Looking back, i dont know why i didnt try out the incognito mode before filing the issue (apart from the work of having to 2fa), sorry, of course that helped: [Privacy Badger](https://www.eff.org/privacybadger) did not allow you to store cookies from accounts.google.com and apis.google.com . Maybe this could go to the faq.
Thanks.
