### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by lartus** [bluzi/awesome-google-tasks#8]
Hi, 
Thanks for this promising project.

For me, the killer app of Google tasks is that you can do everything with the keyboard.

Awesome Google Tasks is very beautiful, but lacks what makes me use Google Apps rather than the hundred of other apps.

**Comment by bluzi** [comment]
Thank you so much for the feedback, I definitely agree, we'll add keyboard shortcuts soon enough.

**Comment by bluzi** [comment]
Alright, we now support basic keyboard support. Can you share your feedback @lartus?
